### ISSUE TITLE
Can not connect from android and iOS

### ISSUE THREAD

**Issue by vityafx** [wheelybird/openvpn-server-ldap-otp#12]
Hi! I was using this image and found that it is impossible to connect to from Android and iOS.
The error on mobile devices is simply "time out". Here is the server log:

```
openvpn_1  | Tue May 14 11:41:24 2019 185.6.247.97:43376 TLS: Initial packet from [AF_INET]185.6.247.97:43376, sid=0ada13fd 8b510653
openvpn_1  | Tue May 14 11:41:24 2019 185.6.247.97:43376 TLS error: The server has no TLS ciphersuites in common with the client. Your --tls-cipher setting might be too restrictive.
openvpn_1  | Tue May 14 11:41:24 2019 185.6.247.97:43376 OpenSSL: error:1408A0C1:SSL routines:SSL3_GET_CLIENT_HELLO:no shared cipher
openvpn_1  | Tue May 14 11:41:24 2019 185.6.247.97:43376 TLS_ERROR: BIO read tls_read_plaintext error
openvpn_1  | Tue May 14 11:41:24 2019 185.6.247.97:43376 TLS Error: TLS object -> incoming plaintext read error
openvpn_1  | Tue May 14 11:41:24 2019 185.6.247.97:43376 TLS Error: TLS handshake failed
openvpn_1  | Tue May 14 11:41:24 2019 185.6.247.97:43376 SIGUSR1[soft,tls-error] received, client-instance restarting
openvpn_1  | Tue May 14 11:42:06 2019 185.6.247.97:58635 TLS: Initial packet from [AF_INET]185.6.247.97:58635, sid=905598d1 34b555fd
openvpn_1  | Tue May 14 11:42:06 2019 185.6.247.97:58635 TLS error: The server has no TLS ciphersuites in common with the client. Your --tls-cipher setting might be too restrictive.
openvpn_1  | Tue May 14 11:42:06 2019 185.6.247.97:58635 OpenSSL: error:1408A0C1:SSL routines:SSL3_GET_CLIENT_HELLO:no shared cipher
openvpn_1  | Tue May 14 11:42:06 2019 185.6.247.97:58635 TLS_ERROR: BIO read tls_read_plaintext error
openvpn_1  | Tue May 14 11:42:06 2019 185.6.247.97:58635 TLS Error: TLS object -> incoming plaintext read error
openvpn_1  | Tue May 14 11:42:06 2019 185.6.247.97:58635 TLS Error: TLS handshake failed
openvpn_1  | Tue May 14 11:42:06 2019 185.6.247.97:58635 SIGUSR1[soft,tls-error] received, client-instance restarting
```

Here is my `yaml`:

```yaml
version: "3"

services:
  openvpn:
    image: wheelybird/openvpn-ldap-otp
    restart: always
    ports:
      - 1194:1194/udp
    volumes:
      - ./config:/etc/openvpn
    environment:
      - OVPN_SERVER_CN=<...>
      - LDAP_URI=ldaps://<...>
      - LDAP_BASE_DN=dc=<...>
      - LDAP_BIND_USER_DN=cn=<...>
      - LDAP_BIND_USER_PASS=<password>
      - LDAP_FILTER=memberOf=<...>
      - KEY_LENGTH=4096
    cap_add:
      - NET_ADMIN
```

What could be the problem?
