### ISSUE TITLE
Routing fails when OVPN_NAT=false

### ISSUE THREAD

**Issue by Fmstrat** [wheelybird/openvpn-server-ldap-otp#22]
Hi,

The following configuration works great, other than the fact that all traffic is going through the VPN:

```
version: '3.7'

services:

  openvpn:
    image: wheelybird/openvpn-ldap-otp
    volumes:
      - openvpn:/etc/openvpn
    ports:
      - "1194:1194/udp"
    environment:
      - "OVPN_SERVER_CN=myhost.domain.com"
      - "LDAP_URI=ldap://myhost.com"
      - "LDAP_BASE_DN=ou=AADDC Users,dc=myhost,dc=com"
      - "LDAP_BIND_USER_DN=AS_bind@myhost.com"
      - "LDAP_BIND_USER_PASS=mypass"
      - "LDAP_LOGIN_ATTRIBUTE=sAMAccountName"
      - "OVPN_DNS_SERVERS=10.10.0.100"
      #- "OVPN_ROUTES=10.10.0.0 255.255.255.0"
      #- "OVPN_NAT=false"
    cap_add:
      - NET_ADMIN
    restart: always

volumes:
  openvpn:
```

However, if I uncomment the two commented lines, my expectation is that I would be able to access the 10.10.0.0 network via the VPN, and the internet via my usual public IP. Instead, the route that is added still has a lower metric than the public route, so I can't access anything.

I then ran across this issue: https://github.com/wheelybird/openvpn-server-ldap-otp/issues/8 and wonder if maybe I'm having the same problem?
