### ISSUE TITLE
iptables v1.4.21: can't initialize iptables table `nat'

### ISSUE THREAD

**Issue by fraserkyle** [wheelybird/openvpn-server-ldap-otp#38]
I am struggling to get the docker image to run using a CentOS 8 host.  I get the below error.

```
iptables v1.4.21: can't initialize iptables table `nat': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
```

My docker-compose.yaml is a follows:
```
version: '3.3'

services:

  vpn:
    image: 'wheelybird/openvpn-ldap-otp:v1.4'
    restart: always
    hostname: 'vpn.d1.innoapps.co.uk'
    environment:
      - OVPN_SERVER_CN=vpn.d1.innoapps.co.uk
      - OVPN_ENABLE_COMPRESSION=false
      - ACTIVE_DIRECTORY_COMPAT_MODE=true
      - USE_CLIENT_CERTIFICATE=false
      - LDAP_URI=ldap://192.168.1.101
      - LDAP_BASE_DN=dc=innoapps,dc=co,dc=uk
      - LDAP_BIND_USER_DN=CN=VPNService,OU=ServiceAccounts,DC=innoapps,DC=co,DC=uk
      - LDAP_BIND_USER_PASS=SECRET
      - OVPN_DNS_SERVERS=192.168.1.101,192.168.1.1
      - OVPN_DNS_SEARCH_DOMAIN=innoapps.co.uk
      - OVPN_PROTOCOL=tcp
    cap_add:
      - NET_ADMIN
    ports:
      - 1194:1194
    dns:
      - 192.168.1.101
      - 192.168.1.1
    dns_search:
      - innoapps.co.uk
```
