### ISSUE TITLE
LDAP login not working.. what could wrong?

### ISSUE THREAD

**Issue by hvanmegen** [wheelybird/openvpn-server-ldap-otp#55]
Hi,

I am having a problem with the docker container; I have set up a docker-compose.yml with the following content on a completely fresh machine:

```
version: '3.3'
services:
    openvpn-ldap-otp:
        container_name: openvpn
        cap_add:
            - NET_ADMIN
        volumes:
            - './files/config:/config'
            - './files/etc-openvpn:/etc/openvpn'
            - './files/lib-modules:/lib/modules'
        ports:
            - '1194:1194/udp'
        environment:
            - 'OVPN_SERVER_CN=vpn.<mydomain>.com'
            - 'LDAP_URI=ldap://10.60.4.5'
            - 'LDAP_BASE_DN=cn=vpn,dc=<mydomain>,dc=nl'
            - 'LDAP_BIND_USER_DN=<admin_user>'
            - 'LDAP_BIND_USER_PASS=<admin_password>'
            - 'LDAP_FILTER=(&(objectClass=posixGroup)(cn=vpn))'
            - 'OVPN_NAT=true'
            - 'OVPN_NETWORK=10.65.0.0 255.255.255.0'
            - 'OVPN_INTERFACE_NAME=tun'
            - 'OVPN_DNS_SERVERS=10.60.4.3,10.60.4.4'
        image: 'wheelybird/openvpn-ldap-otp:v1.4'
        ports:
            - 1194:1194/udp
```
NOTE: All my LAN services (dhcp, ns, ldap, ntp, etc.) are in the 10.60.4.x/24 network, all DHCP clients live the 10.60.0.0/22 range.

During startup, it says this in the logs at the top:
```
openvpn             | iptables: masquerade from 10.65.0.0/24 to everywhere via eth0
openvpn             | iptables: No chain/target/match by that name.
openvpn             | ldap: creating LDAP configuration
openvpn             | pam: enabling LDAP
openvpn             | openvpn: creating server config
openvpn             | openvpn: management interface disabled
```

And this is the error I get when I try to log in: (all 'deadbeef'-things are redacted mac/sids, so is the IP of my neighbours (the one I'm using for testing the VPN) which is not 123.234.123.234)
```
openvpn             | ***************
openvpn             | Running OpenVPN
openvpn             | ***************
openvpn             |
openvpn             | Wed Aug 31 20:58:21 2022 WARNING: POTENTIALLY DANGEROUS OPTION --verify-client-cert none|optional (or --client-cert-not-required) may accept clients which do not present a certificate
openvpn             | Wed Aug 31 20:58:21 2022 OpenVPN 2.4.9 x86_64-redhat-linux-gnu [Fedora EPEL patched] [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Apr 24 2020
openvpn             | Wed Aug 31 20:58:21 2022 library versions: OpenSSL 1.0.2k-fips  26 Jan 2017, LZO 2.06
openvpn             | Wed Aug 31 20:58:21 2022 PLUGIN_INIT: POST /usr/lib64/openvpn/plugins/openvpn-plugin-auth-pam.so '[/usr/lib64/openvpn/plugins/openvpn-plugin-auth-pam.so] [openvpn]' intercepted=PLUGIN_AUTH_USER_PASS_VERIFY
openvpn             | Wed Aug 31 20:58:21 2022 Diffie-Hellman initialized with 2048 bit key
openvpn             | Wed Aug 31 20:58:21 2022 Outgoing Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
openvpn             | Wed Aug 31 20:58:21 2022 Incoming Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
openvpn             | Wed Aug 31 20:58:21 2022 ROUTE_GATEWAY 172.18.0.1/255.255.0.0 IFACE=eth0 HWADDR=02:42:de:ad:be:ef
openvpn             | Wed Aug 31 20:58:21 2022 TUN/TAP device tun0 opened
openvpn             | Wed Aug 31 20:58:21 2022 TUN/TAP TX queue length set to 100
openvpn             | Wed Aug 31 20:58:21 2022 /sbin/ip link set dev tun0 up mtu 1500
openvpn             | Wed Aug 31 20:58:21 2022 /sbin/ip addr add dev tun0 local 10.65.0.1 peer 10.65.0.2
openvpn             | Wed Aug 31 20:58:21 2022 /sbin/ip route add 10.65.0.0/24 via 10.65.0.2
openvpn             | Wed Aug 31 20:58:21 2022 Could not determine IPv4/IPv6 protocol. Using AF_INET
openvpn             | Wed Aug 31 20:58:21 2022 Socket Buffers: R=[212992->212992] S=[212992->212992]
openvpn             | Wed Aug 31 20:58:21 2022 UDPv4 link local (bound): [AF_INET][undef]:1194
openvpn             | Wed Aug 31 20:58:21 2022 UDPv4 link remote: [AF_UNSPEC]
openvpn             | Wed Aug 31 20:58:21 2022 GID set to nobody
openvpn             | Wed Aug 31 20:58:21 2022 UID set to nobody
openvpn             | Wed Aug 31 20:58:21 2022 MULTI: multi_init called, r=256 v=256
openvpn             | Wed Aug 31 20:58:21 2022 IFCONFIG POOL: base=10.65.0.4 size=62, ipv6=0
openvpn             | Wed Aug 31 20:58:21 2022 Initialization Sequence Completed
openvpn             | Wed Aug 31 20:59:48 2022 123.234.123.234:64694 TLS: Initial packet from [AF_INET]123.234.123.234:64694, sid=deadbeef deadbeef
openvpn             | Wed Aug 31 20:59:48 2022 123.234.123.234:64694 peer info: IV_VER=2.5.7
openvpn             | Wed Aug 31 20:59:48 2022 123.234.123.234:64694 peer info: IV_PLAT=win
openvpn             | Wed Aug 31 20:59:48 2022 123.234.123.234:64694 peer info: IV_PROTO=6
openvpn             | Wed Aug 31 20:59:48 2022 123.234.123.234:64694 peer info: IV_NCP=2
openvpn             | Wed Aug 31 20:59:48 2022 123.234.123.234:64694 peer info: IV_CIPHERS=AES-256-GCM:AES-128-GCM:AES-256-CBC
openvpn             | Wed Aug 31 20:59:48 2022 123.234.123.234:64694 peer info: IV_LZ4=1
openvpn             | Wed Aug 31 20:59:48 2022 123.234.123.234:64694 peer info: IV_LZ4v2=1
openvpn             | Wed Aug 31 20:59:48 2022 123.234.123.234:64694 peer info: IV_LZO=1
openvpn             | Wed Aug 31 20:59:48 2022 123.234.123.234:64694 peer info: IV_COMP_STUB=1
openvpn             | Wed Aug 31 20:59:48 2022 123.234.123.234:64694 peer info: IV_COMP_STUBv2=1
openvpn             | Wed Aug 31 20:59:48 2022 123.234.123.234:64694 peer info: IV_TCPNL=1
openvpn             | Wed Aug 31 20:59:48 2022 123.234.123.234:64694 peer info: IV_GUI_VER=OpenVPN_GUI_11
openvpn             | Wed Aug 31 20:59:48 2022 123.234.123.234:64694 peer info: IV_SSO=openurl,crtext
openvpn             | AUTH-PAM: BACKGROUND: user 'hvanmegen' failed to authenticate: Authentication service cannot retrieve authentication info
openvpn             | Wed Aug 31 20:59:57 2022 123.234.123.234:64694 PLUGIN_CALL: POST /usr/lib64/openvpn/plugins/openvpn-plugin-auth-pam.so/PLUGIN_AUTH_USER_PASS_VERIFY status=1
openvpn             | Wed Aug 31 20:59:57 2022 123.234.123.234:64694 PLUGIN_CALL: plugin function PLUGIN_AUTH_USER_PASS_VERIFY failed with status 1: /usr/lib64/openvpn/plugins/openvpn-plugin-auth-pam.so
openvpn             | Wed Aug 31 20:59:57 2022 123.234.123.234:64694 TLS Auth Error: Auth Username/Password verification failed for peer
openvpn             | Wed Aug 31 20:59:57 2022 123.234.123.234:64694 Control Channel: TLSv1.2, cipher TLSv1/SSLv3 DHE-RSA-AES256-SHA
openvpn             | Wed Aug 31 20:59:57 2022 123.234.123.234:64694 Peer Connection Initiated with [AF_INET]123.234.123.234:64694
openvpn             | Wed Aug 31 20:59:59 2022 123.234.123.234:64694 PUSH: Received control message: 'PUSH_REQUEST'
openvpn             | Wed Aug 31 20:59:59 2022 123.234.123.234:64694 Delayed exit in 5 seconds
openvpn             | Wed Aug 31 20:59:59 2022 123.234.123.234:64694 SENT CONTROL [UNDEF]: 'AUTH_FAILED' (status=1)
openvpn             | Wed Aug 31 21:00:04 2022 123.234.123.234:64694 SIGTERM[soft,delayed-exit] received, client-instance exiting
```
Nowhere does it seem to try to connect to LDAP.. I have no idea what is going wrong...

This is what I do when I search inside `home.<mydomain>.nl` with the filter for the group `vpn`:
```
hvanmegen@services:~$ ldapsearch -x -h 10.60.4.5 -b "dc=home,dc=<mydomain>,dc=nl" -s sub "(&(objectClass=posixGroup)(cn=vpn))"
# extended LDIF
#
# LDAPv3
# base <dc=home,dc=<mydomain>,dc=com> with scope subtree
# filter: (&(objectClass=posixGroup)(cn=vpn))
# requesting: ALL
#

# vpn, home.<mydomain>.nl
dn: cn=vpn,dc=home,dc=<mydomain>,dc=nl
gidNumber: 505
cn: vpn
objectClass: posixGroup
objectClass: top
memberUid: hvanmegen

# search result
search: 1
result: 0 Success

# numResponses: 1
# numEntries: 1
```

My username seems to be present in the search results; it's also the username and password combination that I'm trying to enter on the password prompt in my OpenVPN client. I have also tried only logging in with a local user that only exists on that machine 'services', however that also does not work.

NB: pinging my LDAP server from the vpn VM works just fine.. 
```
root@vpn:/opt/openvpn-server
#> ping 10.60.4.5
PING 10.60.4.5 (10.60.4.5) 56(84) bytes of data.
64 bytes from 10.60.4.5 (10.60.4.5): icmp_seq=1 ttl=63 time=0.343 ms
64 bytes from 10.60.4.5 (10.60.4.5): icmp_seq=2 ttl=63 time=0.383 ms
^C
--- 10.60.4.5 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1002ms
rtt min/avg/max/mdev = 0.343/0.363/0.383/0.020 ms
root@vpn:/opt/openvpn-server
#>
```

Any idea what I could be doing wrong?
