### ISSUE TITLE
AUTH-PAM: BACKGROUND: user 'test' failed to authenticate: Authentication service cannot retrieve authentication info

### ISSUE THREAD

**Issue by wad-hongsumin** [wheelybird/openvpn-server-ldap-otp#69]
Hello. I want to connect with Active Directory with LDAP, but I'm stuck. I need help.
1. Active Directory Server Config
  - IP : `10.240.6.5`
  - domain : `wadhou.se`
2. openvpn docker-compose file
```yaml
version: '3.7'
services:
  openvpn:
    container_name: openvpn
    image: 'wheelybird/openvpn-ldap-otp:v1.4'
    environment:
      OVPN_SERVER_CN: testdomain
      OVPN_ENABLE_COMPRESSION: 'false'
      OVPN_NETWORK: 10.255.0.0 255.255.255.0
      OVPN_ROUTES: '10.0.0.0 255.0.0.0, 172.16.0.0 255.240.0.0'
      OVPN_NAT: 'true'
      OVPN_DNS_SERVERS: 10.250.0.2,8.8.8.8,8.8.4.4,168.126.63.1
      OVPN_REGISTER_DNS: 'false'
      USE_CLIENT_CERTIFICATE: 'false'
      OVPN_MANAGEMENT_ENABLE: 'true'
      OVPN_MANAGEMENT_NOAUTH: 'true'
      LDAP_URI: 'ldaps://10.240.6.5'
      LDAP_BASE_DN: 'DC=wadhou,DC=se'
      LDAP_BIND_USER_DN: 'CN=dev,OU=Users,DC=wadhou,DC=se'
      LDAP_BIND_USER_PASS: 'xxx'
      LDAP_TLS_VALIDATE_CERT: 'true'
      LDAP_ENCRYPT_CONNECTION: 'true'
      ACTIVE_DIRECTORY_COMPAT_MODE: 'true'
    cap_add:
      - NET_ADMIN
    volumes:
      - 'openvpn-data:/etc/openvpn'
    ports:
      - '1194:1194/udp'
      - '5555:5555/tcp'
    networks:
      - openvpn
    logging:
      driver: json-file
      options:
        max-size: 8m
        max-file: '10'
    restart: unless-stopped
networks:
  openvpn: {}
volumes:
  openvpn-data: {}
```
3. nslcd file checked in openvpn docker
```sh
uid nslcd
gid ldap

uri ldaps://10.240.6.5

base DC=wadhou,DC=se
scope sub

ldap_version 3

tls_cacertfile /etc/pki/tls/certs/ca-bundle.crt
filter passwd (objectClass=user)
map passwd uid sAMAccountName
binddn CN=dev,OU=Users,DC=wadhou,DC=se
bindpw xxx
```

The dev to be used as the bind user and the test that performed the connection test all exist in the Users OU and belong to the Administrator Group. And the password was never wrong.

Then, when I tried Login as a test user, I found the following errors in openvpn.

```sh
Wed Jun 21 09:38:53 2023 192.168.30.68:58981 TLS: Initial packet from [AF_INET]192.168.30.68:58981, sid=d0afa583 47e82b0d
Wed Jun 21 09:38:53 2023 192.168.30.68:58981 peer info: IV_VER=3.6.7
Wed Jun 21 09:38:53 2023 192.168.30.68:58981 peer info: IV_PLAT=mac
Wed Jun 21 09:38:53 2023 192.168.30.68:58981 peer info: IV_NCP=2
Wed Jun 21 09:38:53 2023 192.168.30.68:58981 peer info: IV_TCPNL=1
Wed Jun 21 09:38:53 2023 192.168.30.68:58981 peer info: IV_PROTO=30
Wed Jun 21 09:38:53 2023 192.168.30.68:58981 peer info: IV_CIPHERS=AES-256-GCM:AES-128-GCM:CHACHA20-POLY1305:AES-256-CBC
Wed Jun 21 09:38:53 2023 192.168.30.68:58981 peer info: IV_GUI_VER=OCmacOS_3.4.2-4547
Wed Jun 21 09:38:53 2023 192.168.30.68:58981 peer info: IV_SSO=webauth,openurl,crtext
AUTH-PAM: BACKGROUND: user 'test' failed to authenticate: Authentication service cannot retrieve authentication info
Wed Jun 21 09:38:53 2023 192.168.30.68:58981 PLUGIN_CALL: POST /usr/lib64/openvpn/plugins/openvpn-plugin-auth-pam.so/PLUGIN_AUTH_USER_PASS_VERIFY status=1
Wed Jun 21 09:38:53 2023 192.168.30.68:58981 PLUGIN_CALL: plugin function PLUGIN_AUTH_USER_PASS_VERIFY failed with status 1: /usr/lib64/openvpn/plugins/openvpn-plugin-auth-pam.so
Wed Jun 21 09:38:53 2023 192.168.30.68:58981 TLS Auth Error: Auth Username/Password verification failed for peer
Wed Jun 21 09:38:53 2023 192.168.30.68:58981 Control Channel: TLSv1.2, cipher TLSv1/SSLv3 DHE-RSA-AES256-SHA
Wed Jun 21 09:38:53 2023 192.168.30.68:58981 Peer Connection Initiated with [AF_INET]192.168.30.68:58981
Wed Jun 21 09:38:53 2023 192.168.30.68:58981 PUSH: Received control message: 'PUSH_REQUEST'
Wed Jun 21 09:38:53 2023 192.168.30.68:58981 Delayed exit in 5 seconds
Wed Jun 21 09:38:53 2023 192.168.30.68:58981 SENT CONTROL [UNDEF]: 'AUTH_FAILED' (status=1)
Wed Jun 21 09:38:58 2023 192.168.30.68:58981 SIGTERM[soft,delayed-exit] received, client-instance exiting
```

For the test, both vpn server and ad server security groups are open, and currently my local is able to priavte communication with the servers.
I confirmed that the ad server and ping / ldap port are communicated in Openvpn docker.

I checked the username and password too many times. There seems to be another reason, but can you guess?

Thx. Sumin
