### ISSUE TITLE
"nslcd: Warning: NSS_LDAP module not loaded: libnss_ldap.so.2: cannot open shared object file: No such file or directory" on initial start

### ISSUE THREAD

**Issue by gschafra** [wheelybird/openvpn-server-ldap-otp#72]
Got "nslcd: Warning: NSS_LDAP module not loaded: libnss_ldap.so.2: cannot open shared object file: No such file or directory" when starting the container (initially?). Is this a problem?

openvpn  | 2d9572a88a8b218d0ffff307e593db00
openvpn  | b9c07630189c2211c2c0b22b5f71e93e
openvpn  | 6c413468b766b72274c9389c31484eed
openvpn  | c1b9c910186f91ce4a6cb5221e95fde5
openvpn  | f4f66a958caa4e7203591209cb5a9f72
openvpn  | a7c6f2eae86e49980d64fb90af938480
openvpn  | 8dd7e564a97c595167e931c03c3262ba
openvpn  | 38e5455631d49c2144dedeb50819b35b
openvpn  | a4bcb1b4d875b4463ea9eea0b76432be
openvpn  | 8efccb6c99170c707bd1120d6664649b
openvpn  | 4bf0f31495130ff2a8fdf4b04e63ff92
openvpn  | 10fd9cd486257dec5be76c16bf855300
openvpn  | 4b863d74155fde724b5bd50a11fa5283
openvpn  | -----END OpenVPN Static key V1-----
openvpn  | </tls-auth>
openvpn  | key-direction 1
openvpn  |
openvpn  | #----------  End of client.ovpn  ----------
openvpn  |
openvpn  | 2023-07-06 09:33:37 - Starting NSCLD... (ignore any NSS_LDAP module warnings)
openvpn  |
**openvpn  | nslcd: Warning: NSS_LDAP module not loaded: libnss_ldap.so.2: cannot open shared object file: No such file or directory**
openvpn  |
openvpn  | 2023-07-06 09:33:37 - Running OpenVPN...
openvpn  |
openvpn  | 2023-07-06 09:33:37 WARNING: --topology net30 support for server configs with IPv4 pools will be removed in a future release. Please migrate to --topology subnet as soon as possible.
openvpn  | 2023-07-06 09:33:37 Note: --cipher is not set. OpenVPN versions before 2.5 defaulted to BF-CBC as fallback when cipher negotiation failed in this case. If you need this fallback please add '--data-ciphers-fallback BF-CBC' to your configuration and/or add BF-CBC to --data-ciphers.
openvpn  | 2023-07-06 09:33:37 Note: NOT using '--topology subnet' disables data channel offload.
openvpn  | 2023-07-06 09:33:37 WARNING: POTENTIALLY DANGEROUS OPTION --verify-client-cert none|optional may accept clients which do not present a certificate
openvpn  | 2023-07-06 09:33:37 OpenVPN 2.6.1 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] [DCO]
openvpn  | 2023-07-06 09:33:37 library versions: OpenSSL 3.0.8 7 Feb 2023, LZO 2.10
openvpn  | 2023-07-06 09:33:37 net_route_v4_best_gw query: dst 0.0.0.0
openvpn  | 2023-07-06 09:33:37 net_route_v4_best_gw result: via 172.19.0.1 dev eth0
openvpn  | 2023-07-06 09:33:37 PLUGIN AUTH-PAM: initialization succeeded (fg)
openvpn  | 2023-07-06 09:33:37 PLUGIN_INIT: POST /usr/lib/x86_64-linux-gnu/openvpn/plugins/openvpn-plugin-auth-pam.so '[/usr/lib/x86_64-linux-gnu/openvpn/plugins/openvpn-plugin-auth-pam.so] [openvpn]' intercepted=PLUGIN_AUTH_USER_PASS_VERIFY

docker-compose.yml:

```yml
version: '3.8'

services:
  openvpn:
    image: wheelybird/openvpn-ldap-otp:v1.8
    container_name: openvpn
    cap_add:
      - NET_ADMIN
    ports:
      - "1194:1194/udp"
    volumes:
      - ./data/conf:/etc/openvpn
    restart: always
    environment:
      - OVPN_SERVER_CN=vpn.xxx.xx
      - LDAP_BASE_DN=OU=xxx,OU=xxx,DC=xxx,DC=local
      - LDAP_FILTER=CN=vpn,OU=xxx,OU=xxx,DC=xxx,DC=local
      - LDAP_URI=ldap://10.x.x.4:389 ldap://10.x.x.15:389
      - LDAP_BIND_USER_DN=CN=...
      - LDAP_BIND_USER_PASS=xxxxxxxx
      - ACTIVE_DIRECTORY_COMPAT_MODE=true
      - OVPN_DNS_SERVERS=xxxxx
      - OVPN_DNS_SEARCH_DOMAIN=xxxx
      - OVPN_REGISTER_DNS=true
      - ENABLE_OTP=true
      - FAIL2BAN_ENABLED=true


```
