### ISSUE TITLE
In docker nat is not working.

### ISSUE THREAD

**Issue by linsir** [wheelybird/openvpn-server-ldap-otp#83]
Hello, first of all, thank you for such a good project. I'm encountering some issues now and I hope to get your help to resolve them.

My docker-compose.yaml is as follows:
```yaml
version: "3"
services:
  openvpn:
    image: wheelybird/openvpn-ldap-otp:v1.8
    container_name: openvpn
    ports:
      - "1194:1194"
    volumes:
      - "./openvpn_data/conf:/etc/openvpn"
    cap_add:
      - NET_ADMIN
    environment:
      - TZ=Asia/Shanghai
      - DEBUG=true
      - OVPN_SERVER_CN=openvpn.seeyon.com
      - OVPN_PROTOCOL=tcp
      - OVPN_NAT=true
      - OVPN_EXTRA=client-to-client
      - OVPN_ROUTES=172.31.22.0 255.255.255.0
      - LDAP_URI=ldap://ldap.xxx.com:389
      - LDAP_BASE_DN=ou=User,dc=xxx,dc=com
      - LDAP_BIND_USER_DN=cn=admin,dc=xxx,dc=com
      - LDAP_BIND_USER_PASS=xxxx
```

1. The client can successfully connect to the openvpn server.
2. The client (10.50.50.1) can ping itself successfully.
3. The openvpn container can ping 172.31.22.1, but the client (10.50.50.1) cannot ping it. I've also checked and there are iptables MASQUERADE rules inside the container.
4. SELinux is disabled on the host machine, and there are iptables modules available.
5. host machine and openvpn container  /proc/sys/net/ipv4/ip_forward is 1.
6. docker version: 25.0.4

What is the reason for this issue and how can I solve it?

Additionally, I have tried running OpenVPN without using containers and using the configuration generated above, and it works normally.
